#
#
#
#
Push-Away-Range: 3
Push-Away-Launch-X: .7
Push-Away-Launch-Y: .5
Wand:
  Material: "RECORD_3"
  Name: "&a&lPushAway Wand"
  Lore:
    - "&7Right click to &epush &7players away!"
    - "&7Works up to &e%range% blocks"
Messages:
  Permission: "&cYou do not have permission to use this command!"
  Given-Wand: "&7You have been given a &a&lPushAway Wand&7!"
  Give-Other-Wand: "&7You have given &e%player% &7a &a&lPushAway Wand&7!"